services:
  db:
    container_name: postgres_container
    image: postgres:18.2
    ports:
      - 5000:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres/data:/var/lib/postgresql
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    networks:
      - my_network
    
  airflow:
    container_name: airflow_container
    image: apache/airflow:slim-3.1.7-python3.13
    ports:
      - 8000:8080
    environment:
      AIRFLOW_DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow@db:5432/airflow_db
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - db
    networks:
      - my_network
    command: >
      bash -c "airflow standalone"
networks:
  my_network:
    driver: bridge