services:
  db:
    container_name: postgres_container
    image: postgres:18.2
    ports:
      - 5000:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres/data:/var/lib/postgres/data