name: ci

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  ci:
    env:
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASS: ${{ secrets.PG_PASSWORD }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start Docker Compose
        run: docker compose up -d --wait

      - name: Run pytest
        run: pytest -q tests